### PR TITLE
event restart command has been fixed

### LINKED ISSUE #156: Fix `event restart` command
Unable to restart resources of a team on an event, 
` hkn event restart <event-tag> <team-id>` command does not work as intended !

### PR DESCRIPTION
**Pull request by mrturkmen06**
#156  issue has been fixed and merged into white-scree-minor-fix branch in order to merge all changes into 1.6.0

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -612,10 +612,9 @@ func (d *daemon) RestartTeamLab(req *pb.RestartTeamLabRequest, resp pb.Daemon_Re
 		return err
 	}
 
-	lab, err := ev.GetHub().GetLabByTag(req.LabTag)
-
-	if err != nil {
-		return err
+ 	lab,ok:=ev.GetLabByTeam(req.TeamId);
```
Comment (tpanum) [inline daemon/daemon.go]: Please make sure that the code is either formatted by `go fmt` or `goimports`, most IDEs should do this on default as you save go files.

File: daemon/daemon_test.go [hunk 2]
```diff
@@ -703,8 +703,6 @@ func TestListEvents(t *testing.T) {
 		count        int
 		err          string
 	}{
-		//{name: "Normal", count: 1},
```
Comment (tpanum) [inline daemon/daemon_test.go]: I think it is dangerous just to remove them. The big question is why are they commented out?

File: daemon/daemon.go (hunk 1 above)
Comment (mrturkmen06) [reply daemon/daemon.go]: 👍🏻

File: daemon/daemon_test.go (hunk 2 above)
Comment (mrturkmen06) [reply daemon/daemon_test.go]: The goroutines which are used in getServer  and grpc.DialContext creates problem somehow, I cannot say how but when I try to run the test gorutouni nill pointer memory error happened.

**Comment by mrturkmen06** [comment]
The main change is that in  current 1.6.0 branch, lab is retrieved by [following command](https://github.com/aau-network-security/haaukins/blob/f95a8dcc0512fe51f6051496e827e4944a0d68c6/daemon/daemon.go#L615) 
``` 
lab, err := ev.GetHub().GetLabByTag(req.LabTag)

```
However, requested information from user was team id not lab tag, for this reason I have modified it into [this](https://github.com/aau-network-security/haaukins/blob/7d2fb1f60abaa3e3ecfe0d32f61a27867ebbf74e/daemon/daemon.go#L615)
```
lab,ok:=ev.GetLabByTeam(req.TeamId);
```

File: daemon/daemon_test.go (hunk 2 above)
Comment (tpanum) [reply daemon/daemon_test.go]: Instead of removing tests, I believe we should try to understand why they fail. So diagnosing this is important from my perspective.

Comment (mrturkmen06) [reply daemon/daemon_test.go]: I will try to fix that 👍🏻 by synchronising the goroutines. :)

Comment (mrturkmen06) [reply daemon/daemon_test.go]: Apparently, getServer function which includes handler, creates problem when creationTime value added to listevents, I will try to find a solution to it.

Comment (mrturkmen06) [reply daemon/daemon_test.go]: fixed
