### PR TITLE
1.6.5

### LINKED ISSUE #288: Dead link in readme (404 - File not found)
**Describe the bug**
The #readme.md file contains a seciton named [Contributing](https://github.com/aau-network-security/haaukins/#contributing) the link should be updated to `https://github.com/aau-network-security/haaukins/blob/master/.github/CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by mrturkmen06**
## Changelog
2b9dfe6 Merge pull request #297 from aau-network-security/integrate-go-releaser
c9990ff certmagic complain fixed
c1055d0 Merge pull request #296 from aau-network-security/dep-update-
b24467c dependencies file updated
891c0d1 version pump 1.6.5
e4fe8f5 team exists template added, required fields updated
1bffebc do not spin up a lab if register values empty
e6b8bf9 [skip ci] Closes #288
37fd216 Merge pull request #285 from aau-network-security/update-logo
537393e Merge pull request #281 from aau-network-security/1.6.4

### CODE REVIEW

File: svcs/ctfd/interception.go [hunk 1]
```diff
@@ -677,3 +679,13 @@ func recordAndServe(next http.Handler, r *http.Request, w http.ResponseWriter, m
 
 	return rec.Result(), body
 }
+
+func isTeamExists(name,email string, ri *registerInterception) bool{
```
Comment (mrturkmen06) [inline svcs/ctfd/interception.go]: will be changed !
