### PR TITLE
Hotfix/fix start event issue #701

### LINKED ISSUE #701: events are saved to db even though it failed to start
**Describe the bug**
The event is saved to database even though it is not successfully created. It can lead some problems when the platform is back, there should not be manual manipulation of database. 

**To Reproduce**
Call create event with some parameters which is actually not present. Anything which causes the platform to crash. 

**Expected behavior**

The platform should handle this issue, like when there is a problem of creating event, all changes (if any) should be reverted. 

**Preliminary check is required**

### PR DESCRIPTION
**Pull request by mrtrkmn**
Closes #701 

- Checking available frontends before actually starting to spin up resources 
- Remove CreateEventFromDB function, add SaveToDB. 
- CreateEventFromDB function was not performing what it says.

### CODE REVIEW

**Comment by Mikkelhost** [comment]
When you are saying checking for available frontends?
Does it check if it has been configured?

I have been experiencing that the webclient displays all files which ends with .ova

The expected behavior i would like is that the webclient only displays the vm's that has been configured in frontends.yml

**Comment by Mikkelhost** [comment]
From my experience, if you try to use a vm that has not been configured in the frontends.yml file it tries to start the vm with 0 memory. Vbox comes back with an error on that one which in turn makes haaukins crash with a nil pointer de-reference panic. Either i would suggest to only try and start the vm if the vm has been configured in the frontends.yml or i would make the function that sets the vm memory or whatever, check if it is 0. If it is 0, it should just default to 4GB or some other default value.

**Comment by mrtrkmn** [comment]
> From my experience, if you try to use a vm that has not been configured in the frontends.yml file it tries to start the vm with 0 memory. Vbox comes back with an error on that one which in turn makes haaukins crash with a nil pointer de-reference panic. Either i would suggest to only try and start the vm if the vm has been configured in the frontends.yml or i would make the function that sets the vm memory or whatever, check if it is 0. If it is 0, it should just default to 4GB or some other default value.

GetAllAvailableFrontends function gets infromation from the frontends.yml file, so from already configured place. However, as you suggested it would be ideal to set default memory if memory is not set correctly, also check if ova file is exists.

**Comment by Mikkelhost** [comment]
> > From my experience, if you try to use a vm that has not been configured in the frontends.yml file it tries to start the vm with 0 memory. Vbox comes back with an error on that one which in turn makes haaukins crash with a nil pointer de-reference panic. Either i would suggest to only try and start the vm if the vm has been configured in the frontends.yml or i would make the function that sets the vm memory or whatever, check if it is 0. If it is 0, it should just default to 4GB or some other default value.
> 
> GetAllAvailableFrontends function gets infromation from the frontends.yml file, so from already configured place. However, as you suggested it would be ideal to set default memory if memory is not set correctly, also check if ova file exists.

Yes!

**Comment by mrtrkmn** [comment]
Roger, I am going to add them.

**Comment by mrtrkmn** [comment]
On top of changes done earlier, default values for frontend image is added and checked during creating an event with last commit. 
What are your feedback on this PR @Lanestolen and @Mikkelhost  ?

File: daemon/daemon_test.go [hunk 1]
```diff
@@ -290,6 +290,7 @@ func (c *counter) Value() (val int32) {
 // RunScheduler runs multiple goroutines
 // in different time intervals
 func TestRunScheduler(t *testing.T) {
+	t.Skipf("Race condition is happenning in this particular test --> needs to be checked")
```
Comment (Lanestolen) [inline daemon/daemon_test.go:293]: Maybe add an issue so this isn't forgotten

File: daemon/event.go [hunk 2]
```diff
@@ -92,6 +94,34 @@ func (d *daemon) CreateEvent(req *pb.CreateEventRequest, resp pb.Daemon_CreateEv
...
+	if err != nil {
+		noEventExist := fmt.Errorf("event does not exist or something is wrong: %v", err)
+		resp.Send(&pb.LabStatus{ErrorMessage: noEventExist.Error()})
+		return noEventExist
+	}
+	if isEventExist.IsExist {
+		resp.Send(&pb.LabStatus{ErrorMessage: NotAvailableTag})
+		return fmt.Errorf(NotAvailableTag)
+	}
+	log.Debug().Msgf("Checked existing events through database.")
```
Comment (Lanestolen) [inline daemon/event.go:113]:
```suggestion
	log.Debug().Msgf("Checked existing events through database.")
	log.Debug().Msg("Checked existing events through database.")
```
Maybe add additional fields for the logging like which tag was used when checking

File: daemon/event.go [hunk 3]
```diff
@@ -92,6 +94,34 @@ func (d *daemon) CreateEvent(req *pb.CreateEventRequest, resp pb.Daemon_CreateEv
...
+		Status: Closed,
+	})
+	if err != nil {
+		noEventExist := fmt.Errorf("event does not exist or something is wrong: %v", err)
+		resp.Send(&pb.LabStatus{ErrorMessage: noEventExist.Error()})
+		return noEventExist
+	}
+	if isEventExist.IsExist {
+		resp.Send(&pb.LabStatus{ErrorMessage: NotAvailableTag})
+		return fmt.Errorf(NotAvailableTag)
```
Comment (Lanestolen) [inline daemon/event.go:111]: Why the format?

File: lab/lab.go [hunk 4]
```diff
@@ -138,13 +140,20 @@ func (l *lab) addFrontend(ctx context.Context, conf store.InstanceConfig, rdpPor
 	if err != nil {
 		return nil, err
 	}
-
+	var mem uint
+	if conf.MemoryMB <= 0 || conf.MemoryMB < defaultImageMEMMB/2 {
+		log.Debug().Msgf("Memory cannot be smaller or equal to zero or less than [ %d ], setting it to default value [ %d ] ", defaultImageMEMMB/2, defaultImageMEMMB)
+		mem = defaultImageMEMMB
+		log.Warn().Msgf("Check frontends configuration file to update memory value of image [ %s ] ", conf.Image)
```
Comment (Lanestolen) [inline lab/lab.go:147]: Use fields instead of the formatting?

File: lab/lab.go [hunk 5]
```diff
@@ -138,13 +140,20 @@ func (l *lab) addFrontend(ctx context.Context, conf store.InstanceConfig, rdpPor
 	if err != nil {
 		return nil, err
 	}
-
+	var mem uint
+	if conf.MemoryMB <= 0 || conf.MemoryMB < defaultImageMEMMB/2 {
+		log.Debug().Msgf("Memory cannot be smaller or equal to zero or less than [ %d ], setting it to default value [ %d ] ", defaultImageMEMMB/2, defaultImageMEMMB)
```
Comment (Lanestolen) [inline lab/lab.go:145]: Is there a reason why memory should be higher than 2gb?, also see commend bellow

File: svcs/guacamole/event.go [hunk 6]
```diff
@@ -95,8 +95,55 @@ type eventHost struct {
 	dir       string
 }
 
-//Create the event configuration for the event got from the DB
-func (eh *eventHost) CreateEventFromEventDB(ctx context.Context, conf store.EventConfig, reCaptchaKey string) (Event, error) {
+func protobufToJson(message proto.Message) (string, error) {
```
Comment (Lanestolen) [inline svcs/guacamole/event.go:98]: Why not proto directly to struct?

File: virtual/vbox/vbox.go [hunk 7]
```diff
@@ -392,6 +394,13 @@ func (lib *vBoxLibrary) getPathFromFile(file string) string {
 
 func (lib *vBoxLibrary) GetCopy(ctx context.Context, conf store.InstanceConfig, vmOpts ...VMOpt) (VM, error) {
 	path := lib.getPathFromFile(conf.Image)
+	// check whether provided image exists or not
+	// if not exits use default image kali.ova
+	if _, err := os.Stat(path); errors.Is(err, os.ErrNotExist) {
+		// image does not exists, continue with default image
+		log.Debug().Msgf("Requested image [ %s ] cannot be found, continuing with default image [ %s ] ", conf.Image, defaultImage)
```
Comment (Lanestolen) [inline virtual/vbox/vbox.go:401]: Use fields in logging
Why have a default image? if no correct image send error and let user try again?

**Review by Lanestolen — CHANGES_REQUESTED** [review]

File: svcs/guacamole/event.go (hunk 6 above)
Comment (mrtrkmn) [reply svcs/guacamole/event.go:98]: protobufToJson did not added on this PR, it was there, so it would be nice to consider it separately in another discussion.

File: virtual/vbox/vbox.go (hunk 7 above)
Comment (mrtrkmn) [reply virtual/vbox/vbox.go:401]: I made some assumptions when doing it. Like I thought that `kali.ova` file is always exists, since it is as for as I know. However, that's right that assumptions are evil in most of the cases. ListFrontends function should list frontends which are configured on frontends.yml and under ova dir together. 

Furthermore, there might be the cases where ova file is corrupted and cannot be imported into the platform environment. In this case, there is a need to check whether provided ova file is corrupted or not. However, this issue itself might include more changes than it should. Therefore, my suggestion for integrity checking would be to do it in separate issue. 

So, currently if no correct image send > then kali ova will be chosen however if there is no kali.ova or corrupted one, then platform might crash. But this is another issue which is not directly related to this issue. 

This PR meant to solve issues like ;

- when create event  cmd send and there is no image configured as given from user then event information should not written to database until event is successfully up and running
- when non-exist frontend chosen, the platform should prefer default one > kali.ova
- when RAM/CPU values are not set correctly on frontends config file, the platform should prefer default values > 4096 MB , 1 CPU 

Of course, this PR is not cure to all issues it may happen but it heals some obvious ones.

File: lab/lab.go (hunk 5 above)
Comment (mrtrkmn) [reply lab/lab.go:145]: Yes, there is a reason actually, there are some resource intensive tools such as Wireshark, Burpsuite and etc, those require more resources to be used in good condition. As for as I know, there are some exercises which require to use some of the mentioned tools above.

File: daemon/event.go (hunk 2 above)
Comment (mrtrkmn) [reply daemon/event.go:113]: Again, these logs are not added in this PR. In my opinion, different issues on the platform should not be touched on a PR which is meant to fix particular issue.

File: daemon/event.go (hunk 3 above)
Comment (mrtrkmn) [reply daemon/event.go:111]: This is not done in this PR, there are general inconsistencies of error handling on the platform itself. Can be handled with a separate issue.

File: lab/lab.go (hunk 5 above)
Comment (Lanestolen) [reply lab/lab.go:145]: Fair, I just wanted the reasoning for setting it to 2gb

File: daemon/event.go (hunk 3 above)
Comment (Lanestolen) [reply daemon/event.go:111]: Okay, if you want it to be handled in another issue i think it should be created

File: daemon/event.go (hunk 2 above)
Comment (Lanestolen) [reply daemon/event.go:113]: Totally fair i just believe that it would be nice to improve the function as a whole when fixing issues caused but it :)

File: daemon/event.go (hunk 3 above)
Comment (mrtrkmn) [reply daemon/event.go:111]: Arranging error handling guideline would be preferred way to go in my opinion. Like we should use `fmt.Errorf` in these particular situation otherwise `errors.New` and etc. Your proposal an issue would be nice to see @Lanestolen :)

File: virtual/vbox/vbox.go (hunk 7 above)
Comment (Lanestolen) [reply virtual/vbox/vbox.go:401]: Im just trying to ensure that no inconvenient errors will happen if someone want to spin up their own instance of haaukins, it is totally right that at our deployment the kali.ova exist but it might not in other places.

I know this is not a part of the issue that this PR is trying to solve, however these changes is included here and therefore I chose to evaluate it as a part of this PR

File: daemon/daemon_test.go (hunk 1 above)
Comment (mrtrkmn) [reply daemon/daemon_test.go:293]: Roger !

File: virtual/vbox/vbox.go (hunk 7 above)
Comment (mrtrkmn) [reply virtual/vbox/vbox.go:401]: Just changed, so when provided frontend is not available on user side, program will check available frontends if there are any ova file available, platform will continue with first available file. 
- If provided ova file cannot be found go for first available frontend
- If frontend did not configured on frontends file, do not produce error instead run it with default values.
What are your feedbacks @Lanestolen & @Mikkelhost ?

**Comment by mrtrkmn** [comment]
I am thinking to merge these changes @Mikkelhost  and @Lanestolen. Just for your information.

**Comment by Lanestolen** [comment]
If @Mikkelhost approves it is fine with me

**Comment by Mikkelhost** [comment]
Looks good to me, i agree on the points stated by @Lanestolen 
Making assumptions is a nono. 

I would just state, that instead of creating an event with a vm which the user did not mean to use, i would respond with an error instead to the user.
Lets take an example:
1. I would like to create an event with 100 capacity and 100 availability like we do for the DDC.
2. I somehow select a vm which is not available.
3. I start the whole event which at times easily takes 30 minutes with this capacity.
4. I discover the vm is wrong, so i now have to shut down the event (30 min - 60 min) to create a new one with the right vm.

Hence i would much rather have it give me an error if i do not specify the right vm or in general if i specify any wrong parameter :)

**Comment by mrtrkmn** [comment]
> Looks good to me, i agree on the points stated by @Lanestolen Making assumptions is a nono.
> 
> I would just state, that instead of creating an event with a vm which the user did not mean to use, i would respond with an error instead to the user. Lets take an example:
> 
> 1. I would like to create an event with 100 capacity and 100 availability like we do for the DDC.
> 2. I somehow select a vm which is not available.
> 3. I start the whole event which at times easily takes 30 minutes with this capacity.
> 4. I discover the vm is wrong, so i now have to shut down the event (30 min - 60 min) to create a new one with the right vm.
> 
> Hence i would much rather have it give me an error if i do not specify the right vm or in general if i specify any wrong parameter :)

Roger, will look into into !

**Comment by mrtrkmn** [comment]
The thing is that, it is not possible to create event with non-existing image through webclient interface, since it only lists ova files which are exist. However, it does not mean, it cannot be created, either using CLI or basic curl requests it is possible for this reason last commit checks image path if does not exists, returns an error. 

nonex

**Comment by Mikkelhost** [comment]
> The thing is that, it is not possible to create event with non-existing image through webclient interface, since it only lists ova files which are exist. However, it does not mean, it cannot be created, either using CLI or basic curl requests it is possible for this reason last commit checks image path if does not exists, returns an error.
> 
> nonex
> 
> @Mikkelhost

This will also cancel event creation right?
It was mainly a concern of user friendliness, all i want to happen is if i try to create an event, and i use values which i expect to work, then i would rather get an error and have to try again than it creating an event for me with some default values :)

**Comment by mrtrkmn** [comment]
> This will also cancel event creation right?

Yes, it is just returning error without initializing anything

**Comment by Mikkelhost** [comment]
Then i think it's looking good :)
